<?php

return [
    'users' => [
        'view-any-user',
        'view-user',
        'create-user',
        'update-user',
        'delete-user',
        'restore-user',
        'force-delete-user',
    ],
    'category' => [
        'view-any-category',
        'view-category',
        'create-category',
        'update-category',
        'delete-category',
        'restore-category',
        'force-delete-category',
    ],
    'maintenance' => [
        'view-any-maintenance',
        'view-maintenance',
        'create-maintenance',
        'update-maintenance',
        'delete-maintenance',
        'restore-maintenance',
        'force-delete-maintenance',
    ],
    'property-type' => [
        'view-any-property-type',
        'view-property-type',
        'create-property-type',
        'update-property-type',
        'delete-property-type',
        'restore-property-type',
        'force-delete-property-type',
    ],
    'company' => [
        'view-any-company',
        'view-company',
        'create-company',
        'update-company',
        'delete-company',
        'restore-company',
        'force-delete-company',
    ],
    'property' => [
        'view-any-property',
        'view-property',
        'create-property',
        'update-property',
        'delete-property',
        'restore-property',
        'force-delete-property',
    ],
    'unit-type' => [
        'view-any-unit-type',
        'view-unit-type',
        'create-unit-type',
        'update-unit-type',
        'delete-unit-type',
        'restore-unit-type',
        'force-delete-unit-type',
    ],
    'unit' => [
        'view-any-unit',
        'view-unit',
        'create-unit',
        'update-unit',
        'delete-unit',
        'restore-unit',
        'force-delete-unit',
    ],
    'prospect' => [
        'view-any-prospect',
        'view-prospect',
        'create-prospect',
        'update-prospect',
        'delete-prospect',
        'restore-prospect',
        'force-delete-prospect',
    ],
    'unit-feature' => [
        'view-any-unit-feature',
        'view-unit-feature',
        'create-unit-feature',
        'update-unit-feature',
        'delete-unit-feature',
        'restore-unit-feature',
        'force-delete-unit-feature',
    ],
    'unit-funishing-item' => [
        'view-any-funishing-item',
        'view-funishing-item',
        'create-funishing-item',
        'update-funishing-item',
        'delete-funishing-item',
        'restore-funishing-item',
        'force-delete-funishing-item',
    ],
    'unit-funishing-category' => [
        'view-any-funishing-category',
        'view-funishing-category',
        'create-funishing-category',
        'update-funishing-category',
        'delete-funishing-category',
        'restore-funishing-category',
        'force-delete-funishing-category',
    ],

];
