<?php

return [

    'view-any-user',
    'view-user',
    'create-user',
    'update-user',
    'delete-user',
    'restore-user',
    'force-delete-user',

    'view-any-category',
    'view-category',
    'create-category',
    'update-category',
    'delete-category',
    'restore-category',
    'force-delete-category',

    'view-any-maintenance',
    'view-maintenance',
    'create-maintenance',
    'update-maintenance',
    'delete-maintenance',
    'restore-maintenance',
    'force-delete-maintenance',

    'view-any-property-type',
    'view-property-type',
    'create-property-type',
    'update-property-type',
    'delete-property-type',
    'restore-property-type',
    'force-delete-property-type',

    'view-any-property',
    'view-property',
    'create-property',
    'update-property',
    'delete-property',
    'restore-property',
    'force-delete-property',

    'view-any-unit-type',
    'view-unit-type',
    'create-unit-type',
    'update-unit-type',
    'delete-unit-type',
    'restore-unit-type',
    'force-delete-unit-type',

    'view-any-unit',
    'view-unit',
    'create-unit',
    'update-unit',
    'delete-unit',
    'restore-unit',
    'force-delete-unit',

    'view-any-prospect',
    'view-prospect',
    'create-prospect',
    'update-prospect',
    'delete-prospect',
    'restore-prospect',
    'force-delete-prospect',
];
