name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "8.0"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: issue_integration
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none
      - name: "Setup CI Authentication"
        run: |
          composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist --no-cache"
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Prepare storage
        run: php artisan storage:link
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
      - name: Start Chrome Driver
        run: vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Run Laravel Server
        run: php artisan serve &
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
      - name: Run Dusk Tests
        run: php artisan dusk
        env:
          APP_URL: "http://127.0.0.1:8000"
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*